version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: 16.14.2
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: yarn install
      - run:
          name: Build Parser
          command: yarn build
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Execute Unit Tests
          command: yarn test --forbid-only
      - run:
          name: Execute Integration Tests
          command: yarn test:integration --forbid-only
      - run:
          name: Release
          command: yarn semantic-release || true
workflows:
    build-and-test:
      jobs:
        - build-and-test
